apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  #googleCloudBuild:
  #  projectId: ticketing-dev-276403
  artifacts:
    - image: tiagovalentimbarreto/ticketing-auth
      #- image: us.gcr.io/ticketing-dev-276403/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: tiagovalentimbarreto/ticketing-client
      #- image: us.gcr.io/ticketing-dev-276403/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: tiagovalentimbarreto/ticketing-tickets
      #- image: us.gcr.io/ticketing-dev-276403/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: tiagovalentimbarreto/ticketing-orders
      #- image: us.gcr.io/ticketing-dev-276403/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: tiagovalentimbarreto/ticketing-expiration
      #- image: us.gcr.io/ticketing-dev-276403/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: tiagovalentimbarreto/ticketing-payments
      #- image: us.gcr.io/ticketing-dev-276403/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
