apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  #googleCloudBuild:
  #  projectId: ticketing-dev-276403
  artifacts:
    - image: tb/auth
      #- image: us.gcr.io/ticketing-dev-276403/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: tb/client
      #- image: us.gcr.io/ticketing-dev-276403/auth
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: tb/tickets
      #- image: us.gcr.io/ticketing-dev-276403/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: tb/orders
      #- image: us.gcr.io/ticketing-dev-276403/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: tb/expiration
      #- image: us.gcr.io/ticketing-dev-276403/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
